# OP-LBS in S-Unit : determine next state

# SU priority
# B-LS-LOG-AD should be later replaced by LBS-AD, when DAT is implemented.

OP-B-FORWARDING = (OP-B-OPC == SU-OPC-ST2) | B-OPCLH
GO-SU		= AA-LD-GO|WW-ST-GO

ACCEPTING-OPC	= (WW-ST-GO ? SU-OPC-ST2 : (A-LS-ST-V?SU-OPC-ST:SU-OPC-LD))
ACCEPTING-AD	= (WW-ST-GO ? STB-AD : AA-EAG-OUTPUT)

# WAIT state : stay/accept from IU/clear

OP-WAIT-STAYS	= OP-B-V-NOCAN & !OP-B-FORWARDING & OP-WAIT-V-NOCAN
OP-WAIT-ACCEPT	= OP-B-V-NOCAN & !OP-B-FORWARDING & GO-SU


OP-WAIT-V    := OP-WAIT-STAYS ? OP-WAIT-V   : OP-WAIT-ACCEPT ? 1 : 0
OP-WAIT-OPC  := OP-WAIT-STAYS ? OP-WAIT-OPC : ACCEPTING-OPC
OP-WAIT-WE   := OP-WAIT-STAYS ? OP-WAIT-WE  : OP-WAIT-ACCEPT ? WW-ST-GO : 0
OP-WAIT-AD   := OP-WAIT-STAYS ? OP-WAIT-AD  : ACCEPTING-AD
OP-WAIT-DT   := OP-WAIT-STAYS ? OP-WAIT-DT  : STB-DT

OP-WAIT-SUBJECT-TO-BC := OP-WAIT-STAYS ? 
				OP-WAIT-SUBJECT-TO-BC & !G-BC-JUST-SOLVED :
	OP-WAIT-ACCEPT ?  AA-LD-GO & A-JB-SUBJECT-TO-BC & !G-BC-JUST-SOLVED : 0


#  OP-B state : stay/accept from IU/shift from WAIT/clear

OP-B-STAYS	= OP-B-V-NOCAN & !OP-B-FORWARDING
#OP-B-ACCEPT	= GO-SU
OP-B-SHIFT 	= OP-WAIT-V-NOCAN


OP-B-V	 := OP-B-STAYS ? OP-B-V   : OP-B-SHIFT ? 1           : GO-SU
OP-B-OPC := OP-B-STAYS ? OP-B-OPC : OP-B-SHIFT ? OP-WAIT-OPC : ACCEPTING-OPC
LBS-WE   := OP-B-STAYS ? LBS-WE   : OP-B-SHIFT ? OP-WAIT-WE  : WW-ST-GO
LBS-AD   := OP-B-STAYS ? LBS-AD   : OP-B-SHIFT ? OP-WAIT-AD  : 
	    GO-SU      ? ACCEPTING-AD : 0
LBS-DT   := OP-B-STAYS ? LBS-DT   : OP-B-SHIFT ? OP-WAIT-DT  : STB-DT

OP-B-SUBJECT-TO-BC  := 
	    OP-B-STAYS ? OP-B-SUBJECT-TO-BC & !G-BC-JUST-SOLVED    :
	    OP-B-SHIFT ? OP-WAIT-SUBJECT-TO-BC & !G-BC-JUST-SOLVED :
			 AA-LD-GO & A-JB-SUBJECT-TO-BC & !G-BC-JUST-SOLVED

