# if-req

#
# Insn Fetch Request
#

# IWQ-FULL

IWQ-FULL = (NIP-0 | NIP-1) & V01 & V23 & V45

# IF-REQ-V/AD/ID decision

IF-INCR-1	= IB-V & (EID == IB-ID) ? IB-AD : EID ? D-IF-AD-B : D-IF-AD-A
IF-INCR-2	= IB-V & (EID == IB-ID) 
		 | NIP-0 | NIP-1 | NIP-2 | NIP-3 | NIP-4 | NIP-5  ? 8 : 0
#ifndef VHDL
IF-INCR-OUT	= add_32_4(IF-INCR-1,IF-INCR-2)
#endif

IF-CASE-START	= START-TRIGGER
IF-CASE-J    	= A-V-NOCAN & A-SET-EAG-TO-TGT
IF-CASE-BA   	= DD-ISSUEING-TAKEN-BRANCH
IF-CASE-BC   	= DD-ISSUEING-UNSOLVED-BC
IF-CASE-NULL 	= IJB-IS-JA | IJB-IS-JL

IF-REQ-V  = IF-CASE-START ? 1 : IF-CASE-J ? A-FWD : IF-CASE-NULL ? 0 : 
	    IF-CASE-BA | IF-CASE-BC ? D-FWD : ! IWQ-FULL

IF-REQ-AD = IF-CASE-START ? PC : IF-CASE-J ? AA-EAG-OUTPUT :
	    IF-CASE-BA | IF-CASE-BC ? DD-TGT : IF-INCR-OUT

IF-REQ-ID = IF-CASE-START ?  0 : IF-CASE-BC ? !EID  : EID

CANCEL-IB = IF-CASE-START | (IF-CASE-BA | IF-CASE-NULL) & (IB-ID == EID)

